import type { Metadata } from "next";
import { Saira } from "next/font/google";

import { Providers } from "./providers";
import Condition from "@/components/Condition";

import "./globals.css";
import StickyNavTabs from "@/components/MobileNavbar";

const saira = Saira({
  variable: "--font-saira",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Andiii",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${saira.variable} antialiased`}>
        <Providers>
          <main className="h-screen lg:flex">
            <Condition />
            <section className="w-full overflow-x-hidden lg:pr-[70px]">
              {children}
            </section>
            <StickyNavTabs />
          </main>
        </Providers>
      </body>
    </html>
  );
}
