import type { Metadata } from "next";
import { Saira } from "next/font/google";

import { Providers } from "./providers";
import Sidebar from "../components/Sidebar";

import "./globals.css";

const saira = Saira({
  variable: "--font-saira",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Andiii",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${saira.variable} antialiased`}>
        <Providers>
          <main className="h-screen lg:flex">
            <Sidebar />
            <section className="w-full overflow-x-hidden">{children}</section>
          </main>
        </Providers>
      </body>
    </html>
  );
}
